modLoader="javafml"
loaderVersion="[28,)" 
issueTrackerURL="https://github.com/feldim2425/MoreOverlays/issues"
[[mods]]
    modId="moreoverlays"
    version="${file.jarVersion}"
    displayName="More Overlays"
    updateJSONURL="https://raw.githubusercontent.com/feldim2425/Mod_Update-JSONs/master/MoreOverlays.json"
    displayURL="https://github.com/feldim2425/MoreOverlays"
    credits="Thanks to all contributors of this project"
    authors="feldim2425"
    description='''
    Adds some overlays from the old (MC 1.7.x) NotEnoughItems Mod:
    * Chunk and Region borders
    * Mob spawn / Ligh overlay
    * Item search when JEI (JustEnoughItems by Mezz) is installed
    '''

[[dependencies.moreoverlays]]
    modId="forge"
    mandatory=true 
    versionRange="[28.1.85,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.moreoverlays]]
    modId="jei"
    mandatory=false
    versionRange="[6.0.0.25,)"
    ordering="NONE"
    side="CLIENT"
